import Sidebar from '@/components/Sidebar'
import '@/styles/globals.css'


export const metadata = {
  title: 'Amazon Webscraper',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex bg-[#F7FBFF] h-screen">
        
          <Sidebar />
          <main className="p-10 max-w-screen-2xl mx-auto overflow-y-auto">
            {children}
          </main>
        
      </body>
    </html>
  )
}
